name: Replace API Key
# on: Controls when the workflow will run
# [push]: Triggers the workflow on push
on: [push, pull_request]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of 2 commands (separated by a new line) using the runners shell
      # Explanation of these commands can be found here: https://chat.openai.com/share/fcdd3614-9c9c-4f3e-bbcf-5ac2631a4351
      - name: Replace API Key
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: (${{ secrets.TASKBONEAPIKEY }}|${{ secrets.SIMPLETEX }}|ababab)
          replace: "YOUR-API-KEY"
          regex: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
